version: '3.5'

services:

  frontend:
    build: ./frontend
    ports:
      - 5000:5000

  redis:
    image: redis
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - database:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=example
      - DB_PASSWORD=example
      - DB_NAME=example
      - DB_HOST=db

  proxy: 
    image: jwilder/nginx-proxy 
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports: 
      - 80:80

volumes:
  database: